export interface IReviewApi {
  id: string
  car: string
  owner: string
  plate: string
  color: string
  status: string
  startTime: string
  endTime: string
  date: string
  description?: string
}

export const reviewData: IReviewApi[] = [
  {
    id: '1',
    car: 'Toyota',
    owner: 'Alice Guzmán',
    plate: 'ABC123',
    color: 'bg-red-200',
    status: 'pending',
    startTime: '08:00',
    endTime: '08:30',
    date: '2024-06-01',
    description: 'Revisión de frenos',
  },
  {
    id: '2',
    car: 'Honda',
    owner: 'Bob Taylor',
    plate: 'XYZ789',
    color: 'bg-blue-200',
    status: 'completed',
    startTime: '08:30',
    endTime: '09:00',
    date: '2024-06-01',
    description: 'Cambio de aceite',
  },
  {
    id: '3',
    car: 'Ford',
    owner: 'Charlie Wington',
    plate: 'LMN456',
    color: 'bg-green-200',
    status: 'pending',
    startTime: '09:00',
    endTime: '09:30',
    date: '2024-06-05',
    description: 'Revisión de suspensión',
  },
  {
    id: '4',
    car: 'BMW',
    owner: 'David Laid',
    plate: 'DEF321',
    color: 'bg-gray-200',
    status: 'completed',
    startTime: '09:30',
    endTime: '10:00',
    date: '2024-06-05',
    description: 'Revisión de motor',
  },
  {
    id: '5',
    car: 'Tesla',
    owner: 'Eve Andino',
    plate: 'GHI654',
    color: 'bg-purple-200',
    status: 'pending',
    startTime: '10:00',
    endTime: '10:30',
    date: '2024-06-10',
    description: 'Actualización de software',
  },
  {
    id: '6',
    car: 'Toyota',
    owner: 'Alice Guzmán',
    plate: 'ABC123',
    color: 'bg-red-200',
    status: 'completed',
    startTime: '10:30',
    endTime: '11:00',
    date: '2024-06-10',
    description: 'Revisión de frenos',
  },
  {
    id: '7',
    car: 'Honda',
    owner: 'Bob Taylor',
    plate: 'XYZ789',
    color: 'bg-blue-200',
    status: 'pending',
    startTime: '11:00',
    endTime: '11:30',
    date: '2024-06-15',
    description: 'Cambio de aceite',
  },
  {
    id: '8',
    car: 'Ford',
    owner: 'Charlie Wington',
    plate: 'LMN456',
    color: 'bg-green-200',
    status: 'completed',
    startTime: '11:30',
    endTime: '12:00',
    date: '2024-06-15',
    description: 'Revisión de suspensión',
  },
  {
    id: '9',
    car: 'BMW',
    owner: 'David Laid',
    plate: 'DEF321',
    color: 'bg-gray-200',
    status: 'pending',
    startTime: '12:00',
    endTime: '12:30',
    date: '2024-06-20',
    description: 'Revisión de motor',
  },
  {
    id: '10',
    car: 'Tesla',
    owner: 'Eve Andino',
    plate: 'GHI654',
    color: 'bg-purple-200',
    status: 'completed',
    startTime: '12:30',
    endTime: '13:00',
    date: '2024-06-20',
    description: 'Actualización de software',
  },
  {
    id: '11',
    car: 'Toyota',
    owner: 'Alice Guzmán',
    plate: 'ABC123',
    color: 'bg-red-200',
    status: 'pending',
    startTime: '13:00',
    endTime: '13:30',
    date: '2024-07-01',
    description: 'Revisión de frenos',
  },
  {
    id: '12',
    car: 'Honda',
    owner: 'Bob Taylor',
    plate: 'XYZ789',
    color: 'bg-blue-200',
    status: 'completed',
    startTime: '13:30',
    endTime: '14:00',
    date: '2024-07-01',
    description: 'Cambio de aceite',
  },
  {
    id: '13',
    car: 'Ford',
    owner: 'Charlie Wington',
    plate: 'LMN456',
    color: 'bg-green-200',
    status: 'pending',
    startTime: '14:00',
    endTime: '14:30',
    date: '2024-07-05',
    description: 'Revisión de suspensión',
  },
  {
    id: '14',
    car: 'BMW',
    owner: 'David Laid',
    plate: 'DEF321',
    color: 'bg-gray-200',
    status: 'completed',
    startTime: '14:30',
    endTime: '15:00',
    date: '2024-07-05',
    description: 'Revisión de motor',
  },
  {
    id: '15',
    car: 'Tesla',
    owner: 'Eve Andino',
    plate: 'GHI654',
    color: 'bg-purple-200',
    status: 'pending',
    startTime: '15:00',
    endTime: '15:30',
    date: '2024-07-10',
    description: 'Actualización de software',
  },
  {
    id: '16',
    car: 'Toyota',
    owner: 'Alice Guzmán',
    plate: 'ABC123',
    color: 'bg-red-200',
    status: 'completed',
    startTime: '15:30',
    endTime: '16:00',
    date: '2024-07-10',
    description: 'Revisión de frenos',
  },
  {
    id: '17',
    car: 'Honda',
    owner: 'Bob Taylor',
    plate: 'XYZ789',
    color: 'bg-blue-200',
    status: 'pending',
    startTime: '16:00',
    endTime: '16:30',
    date: '2024-07-15',
    description: 'Cambio de aceite',
  },
  {
    id: '18',
    car: 'Ford',
    owner: 'Charlie Wington',
    plate: 'LMN456',
    color: 'bg-green-200',
    status: 'completed',
    startTime: '16:30',
    endTime: '17:00',
    date: '2024-07-15',
    description: 'Revisión de suspensión',
  },
  {
    id: '19',
    car: 'BMW',
    owner: 'David Laid',
    plate: 'DEF321',
    color: 'bg-gray-200',
    status: 'pending',
    startTime: '17:00',
    endTime: '17:30',
    date: '2024-07-20',
    description: 'Revisión de motor',
  },
  {
    id: '20',
    car: 'Tesla',
    owner: 'Eve Andino',
    plate: 'GHI654',
    color: 'bg-purple-200',
    status: 'completed',
    startTime: '17:30',
    endTime: '18:00',
    date: '2024-07-20',
    description: 'Actualización de software',
  },
  {
    id: '21',
    car: 'Toyota',
    owner: 'Alice Guzmán',
    plate: 'ABC123',
    color: 'bg-red-200',
    status: 'pending',
    startTime: '08:00',
    endTime: '08:30',
    date: '2024-08-01',
    description: 'Revisión de frenos',
  },
  {
    id: '22',
    car: 'Honda',
    owner: 'Bob Taylor',
    plate: 'XYZ789',
    color: 'bg-blue-200',
    status: 'completed',
    startTime: '08:30',
    endTime: '09:00',
    date: '2024-08-01',
    description: 'Cambio de aceite',
  },
  {
    id: '23',
    car: 'Ford',
    owner: 'Charlie Wington',
    plate: 'LMN456',
    color: 'bg-green-200',
    status: 'pending',
    startTime: '09:00',
    endTime: '09:30',
    date: '2024-08-05',
    description: 'Revisión de suspensión',
  },
  {
    id: '24',
    car: 'BMW',
    owner: 'David Laid',
    plate: 'DEF321',
    color: 'bg-gray-200',
    status: 'completed',
    startTime: '09:30',
    endTime: '10:00',
    date: '2024-08-05',
    description: 'Revisión de motor',
  },
  {
    id: '25',
    car: 'Tesla',
    owner: 'Eve Andino',
    plate: 'GHI654',
    color: 'bg-purple-200',
    status: 'pending',
    startTime: '10:00',
    endTime: '10:30',
    date: '2024-08-10',
    description: 'Actualización de software',
  },
  {
    id: '26',
    car: 'Toyota',
    owner: 'Alice Guzmán',
    plate: 'ABC123',
    color: 'bg-red-200',
    status: 'completed',
    startTime: '10:30',
    endTime: '11:00',
    date: '2024-08-10',
    description: 'Revisión de frenos',
  },
  {
    id: '27',
    car: 'Honda',
    owner: 'Bob Taylor',
    plate: 'XYZ789',
    color: 'bg-blue-200',
    status: 'pending',
    startTime: '11:00',
    endTime: '11:30',
    date: '2024-08-15',
    description: 'Cambio de aceite',
  },
]
