export interface IApiQuote {
  id: string
  date: string
  startTime: string
  endTime: string
  client: string
  mechanic: string
  car: string
  plate?: string
  description: string
  color: string
}

export const apiQuote: IApiQuote[] = [
  {
    id: '1',
    date: '2024-07-10',
    startTime: '08:00',
    endTime: '08:30',
    client: 'John Doe',
    mechanic: 'Juan Perez',
    car: 'Toyota',
    plate: 'ABC-123',
    description: 'Cambio de aceite y filtro',
    color: 'bg-blue-200',
  },
  {
    id: '2',
    date: '2024-07-10',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Jane Smith',
    mechanic: 'Carlos Ruiz',
    car: 'Honda',
    plate: 'XYZ-789',
    description: 'Revisión de frenos',
    color: 'bg-purple-200',
  },
  {
    id: '3',
    date: '2024-07-10',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Alice Johnson',
    mechanic: 'Luis Martinez',
    car: 'Ford',
    plate: 'DEF-456',
    description: 'Cambio de neumáticos',
    color: 'bg-gray-200',
  },
  {
    id: '4',
    date: '2024-07-10',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Bob Brown',
    mechanic: 'Miguel Torres',
    car: 'Chevrolet',
    plate: 'GHI-654',
    description: 'Alineación y balanceo',
    color: 'bg-green-200',
  },
  {
    id: '5',
    date: '2024-07-10',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Charlie Davis',
    mechanic: 'Pedro Gonzalez',
    car: 'Nissan',
    plate: 'JKL-321',
    description: 'Cambio de batería',
    color: 'bg-red-200',
  },
  {
    id: '6',
    date: '2024-07-10',
    startTime: '10:30',
    endTime: '11:00',
    client: 'Emily Wilson',
    mechanic: 'Roberto Lopez',
    car: 'Mazda',
    plate: 'MNO-987',
    description: 'Cambio de aceite',
    color: 'bg-blue-200',
  },
  {
    id: '7',
    date: '2024-07-10',
    startTime: '11:00',
    endTime: '11:30',
    client: 'Frank Clark',
    mechanic: 'Daniel Ramirez',
    car: 'Kia',
    plate: 'PQR-654',
    description: 'Revisión general',
    color: 'bg-purple-200',
  },
  {
    id: '8',
    date: '2024-07-09',
    startTime: '11:30',
    endTime: '12:00',
    client: 'Grace Lee',
    mechanic: 'Santiago Sanchez',
    car: 'Hyundai',
    plate: 'STU-321',
    description: 'Cambio de frenos',
    color: 'bg-gray-200',
  },
  {
    id: '9',
    date: '2024-07-10',
    startTime: '12:00',
    endTime: '12:30',
    client: 'Hank Miller',
    mechanic: 'Oscar Vargas',
    car: 'BMW',
    plate: 'VWX-098',
    description: 'Revisión de suspensión',
    color: 'bg-green-200',
  },
  {
    id: '10',
    date: '2024-07-09',
    startTime: '12:30',
    endTime: '13:00',
    client: 'Ivy Turner',
    mechanic: 'Javier Mendoza',
    car: 'Audi',
    plate: 'YZA-876',
    description: 'Revisión de motor',
    color: 'bg-red-200',
  },
  {
    id: '11',
    date: '2024-07-08',
    startTime: '12:30',
    endTime: '13:00',
    client: 'Jack Anderson',
    mechanic: 'Raul Castillo',
    car: 'Mercedes-Benz',
    plate: 'BCD-543',
    description: 'Cambio de filtros',
    color: 'bg-blue-200',
  },
  {
    id: '12',
    date: '2024-07-10',
    startTime: '10:30',
    endTime: '11:00',
    client: 'Karen Evans',
    mechanic: 'Eduardo Perez',
    car: 'Lexus',
    plate: 'EFG-210',
    description: 'Cambio de aceite y filtro',
    color: 'bg-purple-200',
  },
  {
    id: '13',
    date: '2024-07-09',
    startTime: '14:00',
    endTime: '14:30',
    client: 'Leo Scott',
    mechanic: 'Andres Morales',
    car: 'Volkswagen',
    plate: 'HIJ-678',
    description: 'Revisión de frenos',
    color: 'bg-gray-200',
  },
  {
    id: '14',
    date: '2024-07-10',
    startTime: '14:30',
    endTime: '15:00',
    client: 'Mona Carter',
    mechanic: 'Jorge Diaz',
    car: 'Toyota',
    plate: 'KLM-345',
    description: 'Cambio de neumáticos',
    color: 'bg-green-200',
  },
  {
    id: '15',
    date: '2024-07-10',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Nina Harris',
    mechanic: 'Martin Vega',
    car: 'Honda',
    plate: 'NOP-012',
    description: 'Alineación y balanceo',
    color: 'bg-red-200',
  },
  {
    id: '16',
    date: '2024-07-10',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Oscar Mitchell',
    mechanic: 'Felipe Gomez',
    car: 'Ford',
    plate: 'QRS-890',
    description: 'Cambio de batería',
    color: 'bg-blue-200',
  },
  {
    id: '17',
    date: '2024-07-10',
    startTime: '16:00',
    endTime: '16:30',
    client: 'Paula Moore',
    mechanic: 'Ricardo Hernandez',
    car: 'Chevrolet',
    plate: 'TUV-567',
    description: 'Cambio de aceite',
    color: 'bg-purple-200',
  },
  {
    id: '18',
    date: '2024-07-10',
    startTime: '16:30',
    endTime: '17:00',
    client: 'Quinn Peterson',
    mechanic: 'Samuel Castillo',
    car: 'Nissan',
    plate: 'WXY-234',
    description: 'Revisión general',
    color: 'bg-gray-200',
  },
  {
    id: '19',
    date: '2024-07-10',
    startTime: '17:00',
    endTime: '17:30',
    client: 'Rita Reed',
    mechanic: 'Carlos Ortiz',
    car: 'Mazda',
    plate: 'ZAB-901',
    description: 'Cambio de frenos',
    color: 'bg-green-200',
  },
  {
    id: '20',
    date: '2024-07-10',
    startTime: '17:30',
    endTime: '18:00',
    client: 'Steve Thompson',
    mechanic: 'Ivan Paredes',
    car: 'Kia',
    plate: 'CDE-678',
    description: 'Revisión de suspensión',
    color: 'bg-red-200',
  },
  {
    id: '21',
    date: '2024-07-12',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Tom Wright',
    mechanic: 'Luis Torres',
    car: 'Hyundai',
    plate: 'FGH-345',
    description: 'Revisión de motor',
    color: 'bg-blue-200',
  },
  {
    id: '22',
    date: '2024-07-12',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Uma White',
    mechanic: 'Diego Ramirez',
    car: 'BMW',
    plate: 'IJK-012',
    description: 'Cambio de filtros',
    color: 'bg-purple-200',
  },
  {
    id: '23',
    date: '2024-07-12',
    startTime: '09:00',
    endTime: '09:30',
    client: 'Vic Young',
    mechanic: 'Adrian Flores',
    car: 'Audi',
    plate: 'LMN-789',
    description: 'Cambio de aceite y filtro',
    color: 'bg-gray-200',
  },
  {
    id: '24',
    date: '2024-07-12',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Wendy Brown',
    mechanic: 'Fernando Castro',
    car: 'Mercedes-Benz',
    plate: 'OPQ-456',
    description: 'Revisión de frenos',
    color: 'bg-green-200',
  },
  {
    id: '25',
    date: '2024-07-12',
    startTime: '10:00',
    endTime: '10:30',
    client: 'Xander Hall',
    mechanic: 'Victor Mendez',
    car: 'Lexus',
    plate: 'RST-123',
    description: 'Cambio de neumáticos',
    color: 'bg-red-200',
  },
  {
    id: '26',
    date: '2024-07-12',
    startTime: '10:30',
    endTime: '11:00',
    client: 'Yara Black',
    mechanic: 'Gabriel Ramos',
    car: 'Volkswagen',
    plate: 'UVW-890',
    description: 'Alineación y balanceo',
    color: 'bg-blue-200',
  },
  {
    id: '27',
    date: '2024-07-12',
    startTime: '11:00',
    endTime: '11:30',
    client: 'Zane Green',
    mechanic: 'Hector Chavez',
    car: 'Toyota',
    plate: 'XYZ-567',
    description: 'Cambio de batería',
    color: 'bg-purple-200',
  },
  {
    id: '28',
    date: '2024-07-12',
    startTime: '11:30',
    endTime: '12:00',
    client: 'Amy Hughes',
    mechanic: 'Julio Ramos',
    car: 'Honda',
    plate: 'ABC-234',
    description: 'Cambio de aceite',
    color: 'bg-gray-200',
  },
  {
    id: '29',
    date: '2024-07-12',
    startTime: '12:00',
    endTime: '12:30',
    client: 'Ben Ingram',
    mechanic: 'Kevin Ruiz',
    car: 'Ford',
    plate: 'DEF-901',
    description: 'Revisión general',
    color: 'bg-green-200',
  },
  {
    id: '30',
    date: '2024-07-12',
    startTime: '12:30',
    endTime: '13:00',
    client: 'Cathy Jackson',
    mechanic: 'Manuel Hernandez',
    car: 'Chevrolet',
    plate: 'GHI-678',
    description: 'Cambio de frenos',
    color: 'bg-red-200',
  },
  {
    id: '31',
    date: '2024-07-12',
    startTime: '12:30',
    endTime: '13:00',
    client: 'David King',
    mechanic: 'Raul Espinoza',
    car: 'Nissan',
    plate: 'JKL-345',
    description: 'Revisión de suspensión',
    color: 'bg-blue-200',
  },
  {
    id: '32',
    date: '2024-07-12',
    startTime: '10:30',
    endTime: '11:00',
    client: 'Eva Lewis',
    mechanic: 'Francisco Vega',
    car: 'Mazda',
    plate: 'MNO-012',
    description: 'Revisión de motor',
    color: 'bg-purple-200',
  },
  {
    id: '33',
    date: '2024-07-12',
    startTime: '14:00',
    endTime: '14:30',
    client: 'Fred Martinez',
    mechanic: 'Esteban Torres',
    car: 'Kia',
    plate: 'PQR-789',
    description: 'Cambio de filtros',
    color: 'bg-gray-200',
  },
  {
    id: '34',
    date: '2024-07-12',
    startTime: '14:30',
    endTime: '15:00',
    client: 'Gina Nelson',
    mechanic: 'Miguel Ramirez',
    car: 'Hyundai',
    plate: 'STU-456',
    description: 'Cambio de aceite y filtro',
    color: 'bg-green-200',
  },
  {
    id: '35',
    date: '2024-07-12',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Henry Olson',
    mechanic: 'Ricardo Vargas',
    car: 'BMW',
    plate: 'VWX-123',
    description: 'Revisión de frenos',
    color: 'bg-red-200',
  },
  {
    id: '36',
    date: '2024-07-11',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Iris Patterson',
    mechanic: 'Carlos Martinez',
    car: 'Audi',
    plate: 'YZA-890',
    description: 'Cambio de neumáticos',
    color: 'bg-blue-200',
  },
  {
    id: '37',
    date: '2024-07-11',
    startTime: '16:00',
    endTime: '16:30',
    client: 'Jack Quinn',
    mechanic: 'Juan Gomez',
    car: 'Mercedes-Benz',
    plate: 'BCD-567',
    description: 'Alineación y balanceo',
    color: 'bg-purple-200',
  },
  {
    id: '38',
    date: '2024-07-12',
    startTime: '16:30',
    endTime: '17:00',
    client: 'Karen Roberts',
    mechanic: 'Luis Perez',
    car: 'Lexus',
    plate: 'EFG-234',
    description: 'Cambio de batería',
    color: 'bg-gray-200',
  },
  {
    id: '39',
    date: '2024-07-11',
    startTime: '17:00',
    endTime: '17:30',
    client: 'Leo Stevens',
    mechanic: 'David Gonzalez',
    car: 'Volkswagen',
    plate: 'HIJ-901',
    description: 'Cambio de aceite',
    color: 'bg-green-200',
  },
  {
    id: '40',
    date: '2024-07-12',
    startTime: '17:30',
    endTime: '18:00',
    client: 'Mona Taylor',
    mechanic: 'Carlos Torres',
    car: 'Toyota',
    plate: 'KLM-678',
    description: 'Revisión general',
    color: 'bg-red-200',
  },
  {
    id: '41',
    date: '2024-07-15',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Nina Walker',
    mechanic: 'Jose Hernandez',
    car: 'Honda',
    plate: 'NOP-345',
    description: 'Cambio de frenos',
    color: 'bg-blue-200',
  },
  {
    id: '42',
    date: '2024-07-15',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Oscar Young',
    mechanic: 'Sergio Ramirez',
    car: 'Ford',
    plate: 'QRS-012',
    description: 'Revisión de suspensión',
    color: 'bg-purple-200',
  },
  {
    id: '43',
    date: '2024-07-15',
    startTime: '09:00',
    endTime: '09:30',
    client: 'Paula Allen',
    mechanic: 'Raul Torres',
    car: 'Chevrolet',
    plate: 'TUV-789',
    description: 'Revisión de motor',
    color: 'bg-gray-200',
  },
  {
    id: '44',
    date: '2024-07-15',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Quinn Baker',
    mechanic: 'Jose Castillo',
    car: 'Nissan',
    plate: 'WXY-456',
    description: 'Cambio de filtros',
    color: 'bg-green-200',
  },
  {
    id: '45',
    date: '2024-07-15',
    startTime: '10:00',
    endTime: '10:30',
    client: 'Rita Campbell',
    mechanic: 'Miguel Flores',
    car: 'Mazda',
    plate: 'ZAB-123',
    description: 'Cambio de aceite y filtro',
    color: 'bg-red-200',
  },
  {
    id: '46',
    date: '2024-07-15',
    startTime: '10:30',
    endTime: '11:00',
    client: 'Steve Davis',
    mechanic: 'Julio Gomez',
    car: 'Kia',
    plate: 'CDE-890',
    description: 'Revisión de frenos',
    color: 'bg-blue-200',
  },
  {
    id: '47',
    date: '2024-07-15',
    startTime: '11:00',
    endTime: '11:30',
    client: 'Tom Edwards',
    mechanic: 'Gabriel Hernandez',
    car: 'Hyundai',
    plate: 'FGH-567',
    description: 'Cambio de neumáticos',
    color: 'bg-purple-200',
  },
  {
    id: '48',
    date: '2024-07-15',
    startTime: '11:30',
    endTime: '12:00',
    client: 'Uma Fox',
    mechanic: 'Fernando Perez',
    car: 'BMW',
    plate: 'IJK-234',
    description: 'Alineación y balanceo',
    color: 'bg-gray-200',
  },
  {
    id: '49',
    date: '2024-07-15',
    startTime: '12:00',
    endTime: '12:30',
    client: 'Vic Green',
    mechanic: 'Luis Rodriguez',
    car: 'Audi',
    plate: 'LMN-901',
    description: 'Cambio de batería',
    color: 'bg-green-200',
  },
  {
    id: '50',
    date: '2024-07-15',
    startTime: '12:30',
    endTime: '13:00',
    client: 'Wendy Hill',
    mechanic: 'Raul Martinez',
    car: 'Mercedes-Benz',
    plate: 'OPQ-678',
    description: 'Cambio de aceite',
    color: 'bg-red-200',
  },
  {
    id: '51',
    date: '2024-06-17',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Mark Wood',
    mechanic: 'Hugo Alvarez',
    car: 'Toyota',
    plate: 'RST-234',
    description: 'Cambio de aceite y filtro',
    color: 'bg-blue-200',
  },
  {
    id: '52',
    date: '2024-06-17',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Sara Lane',
    mechanic: 'Santiago Jimenez',
    car: 'Honda',
    plate: 'UVW-567',
    description: 'Revisión de frenos',
    color: 'bg-purple-200',
  },
  {
    id: '53',
    date: '2024-06-17',
    startTime: '09:00',
    endTime: '09:30',
    client: 'Paul Adams',
    mechanic: 'Miguel Herrera',
    car: 'Ford',
    plate: 'XYZ-890',
    description: 'Cambio de neumáticos',
    color: 'bg-gray-200',
  },
  {
    id: '54',
    date: '2024-06-17',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Lara Clark',
    mechanic: 'Julian Diaz',
    car: 'Chevrolet',
    plate: 'ABC-123',
    description: 'Alineación y balanceo',
    color: 'bg-green-200',
  },
  {
    id: '55',
    date: '2024-06-17',
    startTime: '10:00',
    endTime: '10:30',
    client: 'Nina Allen',
    mechanic: 'Carlos Vasquez',
    car: 'Nissan',
    plate: 'DEF-456',
    description: 'Cambio de batería',
    color: 'bg-red-200',
  },
  {
    id: '56',
    date: '2024-06-18',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Oliver King',
    mechanic: 'Roberto Molina',
    car: 'Mazda',
    plate: 'GHI-789',
    description: 'Cambio de aceite',
    color: 'bg-blue-200',
  },
  {
    id: '57',
    date: '2024-06-18',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Emma Davis',
    mechanic: 'Ricardo Morales',
    car: 'Kia',
    plate: 'JKL-012',
    description: 'Revisión general',
    color: 'bg-purple-200',
  },
  {
    id: '58',
    date: '2024-06-18',
    startTime: '09:00',
    endTime: '09:30',
    client: 'Lucas Hill',
    mechanic: 'Luis Fernandez',
    car: 'Hyundai',
    plate: 'MNO-345',
    description: 'Cambio de frenos',
    color: 'bg-gray-200',
  },
  {
    id: '59',
    date: '2024-06-18',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Mia Wilson',
    mechanic: 'Daniel Gutierrez',
    car: 'BMW',
    plate: 'PQR-678',
    description: 'Revisión de suspensión',
    color: 'bg-green-200',
  },
  {
    id: '60',
    date: '2024-06-18',
    startTime: '10:00',
    endTime: '10:30',
    client: 'Ethan Clark',
    mechanic: 'Javier Lopez',
    car: 'Audi',
    plate: 'STU-901',
    description: 'Revisión de motor',
    color: 'bg-red-200',
  },
  {
    id: '61',
    date: '2024-06-19',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Grace Allen',
    mechanic: 'Diego Sanchez',
    car: 'Mercedes-Benz',
    plate: 'VWX-234',
    description: 'Cambio de filtros',
    color: 'bg-blue-200',
  },
  {
    id: '62',
    date: '2024-06-19',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Henry Martinez',
    mechanic: 'Jose Reyes',
    car: 'Lexus',
    plate: 'YZA-567',
    description: 'Cambio de aceite y filtro',
    color: 'bg-purple-200',
  },
  {
    id: '63',
    date: '2024-06-19',
    startTime: '09:00',
    endTime: '09:30',
    client: 'Isla Nelson',
    mechanic: 'Andres Ortiz',
    car: 'Volkswagen',
    plate: 'BCD-890',
    description: 'Revisión de frenos',
    color: 'bg-gray-200',
  },
  {
    id: '64',
    date: '2024-06-19',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Jack Thompson',
    mechanic: 'Fernando Diaz',
    car: 'Toyota',
    plate: 'EFG-123',
    description: 'Cambio de neumáticos',
    color: 'bg-green-200',
  },
  {
    id: '65',
    date: '2024-06-19',
    startTime: '10:00',
    endTime: '10:30',
    client: 'Kate White',
    mechanic: 'Raul Castillo',
    car: 'Honda',
    plate: 'HIJ-456',
    description: 'Alineación y balanceo',
    color: 'bg-red-200',
  },
  {
    id: '66',
    date: '2024-07-01',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Liam Scott',
    mechanic: 'Felipe Gonzalez',
    car: 'Ford',
    plate: 'KLM-789',
    description: 'Cambio de batería',
    color: 'bg-blue-200',
  },
  {
    id: '67',
    date: '2024-07-01',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Mila Young',
    mechanic: 'Victor Mendez',
    car: 'Chevrolet',
    plate: 'NOP-012',
    description: 'Cambio de aceite',
    color: 'bg-purple-200',
  },
  {
    id: '68',
    date: '2024-07-01',
    startTime: '09:00',
    endTime: '09:30',
    client: 'Noah Brown',
    mechanic: 'Gabriel Ramos',
    car: 'Nissan',
    plate: 'QRS-345',
    description: 'Revisión general',
    color: 'bg-gray-200',
  },
  {
    id: '69',
    date: '2024-07-01',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Olivia Green',
    mechanic: 'Hector Chavez',
    car: 'Mazda',
    plate: 'TUV-678',
    description: 'Cambio de frenos',
    color: 'bg-green-200',
  },
  {
    id: '70',
    date: '2024-07-01',
    startTime: '10:00',
    endTime: '10:30',
    client: 'Patrick Lopez',
    mechanic: 'Julio Ramos',
    car: 'Kia',
    plate: 'WXY-901',
    description: 'Revisión de suspensión',
    color: 'bg-red-200',
  },
  {
    id: '71',
    date: '2024-07-03',
    startTime: '08:00',
    endTime: '08:30',
    client: 'Quinn Davis',
    mechanic: 'Fernando Castro',
    car: 'Hyundai',
    plate: 'ZAB-234',
    description: 'Revisión de motor',
    color: 'bg-blue-200',
  },
  {
    id: '72',
    date: '2024-07-03',
    startTime: '08:30',
    endTime: '09:00',
    client: 'Ryan Lewis',
    mechanic: 'Manuel Hernandez',
    car: 'BMW',
    plate: 'CDE-567',
    description: 'Cambio de filtros',
    color: 'bg-purple-200',
  },
  {
    id: '73',
    date: '2024-07-03',
    startTime: '09:00',
    endTime: '09:30',
    client: 'Sophie Clark',
    mechanic: 'Kevin Ruiz',
    car: 'Audi',
    plate: 'FGH-890',
    description: 'Cambio de aceite y filtro',
    color: 'bg-gray-200',
  },
  {
    id: '74',
    date: '2024-07-03',
    startTime: '09:30',
    endTime: '10:00',
    client: 'Thomas Allen',
    mechanic: 'Raul Espinoza',
    car: 'Mercedes-Benz',
    plate: 'IJK-123',
    description: 'Revisión de frenos',
    color: 'bg-green-200',
  },
  {
    id: '75',
    date: '2024-07-03',
    startTime: '10:00',
    endTime: '10:30',
    client: 'Una Hill',
    mechanic: 'Francisco Vega',
    car: 'Lexus',
    plate: 'LMN-456',
    description: 'Cambio de neumáticos',
    color: 'bg-red-200',
  },
]
