name: Create Branch for New Issue

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create new branch
        run: |
          git checkout -b ${{ github.event.issue.title }}
          git push origin ${{ github.event.issue.title }}

      - name: Comment on issue
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments \
            -d "{\"body\": \"Branch created: ${{ github.event.issue.title }}\"}"
