export interface IApiAdminQuotes {
  id: number
  date: string
  startTime: string
  title: string
  description: string
  color: string
}

export const apiAdminQuotes: IApiAdminQuotes[] = [
  {
    id: 1,
    date: '2024-06-01',
    startTime: '09:00',
    title: 'Reunión de ingresos',
    description: 'Revisión mensual de ingresos y facturación.',
    color: 'bg-green-200',
  },
  {
    id: 2,
    date: '2024-06-03',
    startTime: '10:00',
    title: 'Compras de repuestos',
    description: 'Planificación de compras de repuestos para el próximo mes.',
    color: 'bg-red-200',
  },
  {
    id: 3,
    date: '2024-06-05',
    startTime: '11:00',
    title: 'Capacitación de personal',
    description: 'Sesión de capacitación sobre nuevas técnicas de reparación.',
    color: 'bg-orange-200',
  },
  {
    id: 4,
    date: '2024-06-07',
    startTime: '09:30',
    title: 'Reunión con proveedores',
    description: 'Negociación de precios y condiciones con proveedores de repuestos.',
    color: 'bg-green-200',
  },
  {
    id: 5,
    date: '2024-06-09',
    startTime: '08:30',
    title: 'Auditoría interna',
    description: 'Revisión interna de procesos y calidad.',
    color: 'bg-red-200',
  },
  {
    id: 6,
    date: '2024-06-11',
    startTime: '10:30',
    title: 'Revisión de inventario',
    description: 'Control y actualización del inventario de repuestos.',
    color: 'bg-orange-200',
  },
  {
    id: 7,
    date: '2024-06-13',
    startTime: '14:00',
    title: 'Reunión de marketing',
    description: 'Planificación de estrategias de marketing para el próximo trimestre.',
    color: 'bg-green-200',
  },
  {
    id: 8,
    date: '2024-06-15',
    startTime: '09:00',
    title: 'Evaluación de desempeño',
    description: 'Revisión del desempeño del personal y planes de mejora.',
    color: 'bg-red-200',
  },
  {
    id: 9,
    date: '2024-06-17',
    startTime: '13:00',
    title: 'Actualización de software',
    description: 'Implementación de nuevas versiones de software de gestión.',
    color: 'bg-orange-200',
  },
  {
    id: 10,
    date: '2024-06-19',
    startTime: '10:00',
    title: 'Reunión de seguridad',
    description: 'Evaluación y mejora de las medidas de seguridad en el taller.',
    color: 'bg-green-200',
  },
  {
    id: 11,
    date: '2024-06-21',
    startTime: '15:00',
    title: 'Revisión de políticas',
    description: 'Actualización de políticas internas y procedimientos.',
    color: 'bg-red-200',
  },
  {
    id: 12,
    date: '2024-06-23',
    startTime: '09:00',
    title: 'Reunión de finanzas',
    description: 'Revisión del estado financiero del taller.',
    color: 'bg-orange-200',
  },
  {
    id: 13,
    date: '2024-06-25',
    startTime: '10:00',
    title: 'Planificación de proyectos',
    description: 'Planificación de nuevos proyectos de mejora y expansión.',
    color: 'bg-green-200',
  },
  {
    id: 14,
    date: '2024-06-27',
    startTime: '11:00',
    title: 'Evaluación de clientes',
    description: 'Análisis de la satisfacción del cliente y feedback.',
    color: 'bg-red-200',
  },
  {
    id: 15,
    date: '2024-06-29',
    startTime: '09:00',
    title: 'Reunión de equipo',
    description: 'Revisión general de objetivos y metas del equipo.',
    color: 'bg-orange-200',
  },
  {
    id: 16,
    date: '2024-07-01',
    startTime: '08:00',
    title: 'Reunión de ingresos',
    description: 'Revisión mensual de ingresos y facturación.',
    color: 'bg-green-200',
  },
  {
    id: 17,
    date: '2024-07-03',
    startTime: '09:30',
    title: 'Compras de repuestos',
    description: 'Planificación de compras de repuestos para el próximo mes.',
    color: 'bg-red-200',
  },
  {
    id: 18,
    date: '2024-07-05',
    startTime: '10:00',
    title: 'Capacitación de personal',
    description: 'Sesión de capacitación sobre nuevas técnicas de reparación.',
    color: 'bg-orange-200',
  },
  {
    id: 19,
    date: '2024-07-07',
    startTime: '11:00',
    title: 'Reunión con proveedores',
    description: 'Negociación de precios y condiciones con proveedores de repuestos.',
    color: 'bg-green-200',
  },
  {
    id: 20,
    date: '2024-07-09',
    startTime: '13:00',
    title: 'Auditoría interna',
    description: 'Revisión interna de procesos y calidad.',
    color: 'bg-red-200',
  },
  {
    id: 21,
    date: '2024-07-11',
    startTime: '14:30',
    title: 'Revisión de inventario',
    description: 'Control y actualización del inventario de repuestos.',
    color: 'bg-orange-200',
  },
  {
    id: 22,
    date: '2024-07-13',
    startTime: '15:00',
    title: 'Reunión de marketing',
    description: 'Planificación de estrategias de marketing para el próximo trimestre.',
    color: 'bg-green-200',
  },
  {
    id: 23,
    date: '2024-07-15',
    startTime: '08:00',
    title: 'Evaluación de desempeño',
    description: 'Revisión del desempeño del personal y planes de mejora.',
    color: 'bg-red-200',
  },
  {
    id: 24,
    date: '2024-07-17',
    startTime: '09:00',
    title: 'Actualización de software',
    description: 'Implementación de nuevas versiones de software de gestión.',
    color: 'bg-orange-200',
  },
  {
    id: 25,
    date: '2024-07-19',
    startTime: '10:30',
    title: 'Reunión de seguridad',
    description: 'Evaluación y mejora de las medidas de seguridad en el taller.',
    color: 'bg-green-200',
  },
  {
    id: 26,
    date: '2024-07-21',
    startTime: '11:00',
    title: 'Revisión de políticas',
    description: 'Actualización de políticas internas y procedimientos.',
    color: 'bg-red-200',
  },
  {
    id: 27,
    date: '2024-07-23',
    startTime: '09:00',
    title: 'Reunión de finanzas',
    description: 'Revisión del estado financiero del taller.',
    color: 'bg-orange-200',
  },
  {
    id: 28,
    date: '2024-07-25',
    startTime: '10:00',
    title: 'Planificación de proyectos',
    description: 'Planificación de nuevos proyectos de mejora y expansión.',
    color: 'bg-green-200',
  },
  {
    id: 29,
    date: '2024-07-27',
    startTime: '08:30',
    title: 'Evaluación de clientes',
    description: 'Análisis de la satisfacción del cliente y feedback.',
    color: 'bg-red-200',
  },
  {
    id: 30,
    date: '2024-07-29',
    startTime: '09:00',
    title: 'Reunión de equipo',
    description: 'Revisión general de objetivos y metas del equipo.',
    color: 'bg-orange-200',
  },
]
